# Generated by Django 4.0.1 on 2022-01-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandrillResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('event_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('ts', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('message_ts', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sender', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tags', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('message_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('time_opened', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('time_clicked', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('url_clicked', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
