# Generated by Django 4.0.1 on 2022-01-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_alter_mandrillresponse_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandrillresponse',
            name='id',
        ),
        migrations.AlterField(
            model_name='mandrillresponse',
            name='message_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
